### ISSUE TITLE
[FEED] Windows agent module missing

### ISSUE THREAD

**Issue by cbirkenbeul** [Checkmk/ansible-collection-tribe29.checkmk#163]
Hello,

i just came up via the check_mk forum to install the agent on my windows server. Unfortunately this collection does not provide a module to install check_mk on these OS.

If its not planed, it would be nice if there is any information on the readme that its not included. 

Thanks.

**Comment by robin-tribe29** [comment]
Hi Christian and thanks for your feedback!

There is however a minor issue: If we list all the operating systems, that are unsupported by the agent and/or server role, the README would get quite extensive, if you get my drift. :)

We are lacking support for Windows right now, because I have no setup to try this on. There is a branch for Windows support already, and we are just waiting for someone (inside or outside tribe29) to pick it up.
Feel free to take on the challenge. :muscle:

**Comment by cbirkenbeul** [comment]
Hey,
to list all unsupported OS is not a good idea, i get it. But Windows is a quite popular OS.

I'm a ansible newbe but i will try the windows-agent branch, test it and reporting back.

**Comment by robin-tribe29** [comment]
I hear you. But I am confident, that we will have Windows support rather sooner than later, so I did not mention it explicitly.

The branch is not functional currently, but it might be a good starting point.

**Comment by muehlings** [comment]
Hello @cbirkenbeul 

Can have a look at https://github.com/tribe29/ansible-collection-tribe29.checkmk/pull/187 and test or is it no longer interesting for you?

**Comment by HaZet1968** [comment]
Is here something going on? I made an evil workaround for this missing feature, but I am not glad with it. Would be much more nice to get Windows Support here

**Comment by robin-tribe29** [comment]
We have no resources currently and as the changes proposed in #187 are rather complex, we need some time to integrate those. But you can work with that PR and provide feedback there.
